"""add report tasks

Revision ID: 1d0443e2a302
Revises: d376e0d12912
Create Date: 2026-09-15 12:44:25.230116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0443e2a302'
down_revision: Union[str, Sequence[str], None] = 'd376e0d12912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_tasks_celery_task_id'), 'report_tasks', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_report_tasks_id'), 'report_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_report_tasks_user_id'), 'report_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_tasks_user_id'), table_name='report_tasks')
    op.drop_index(op.f('ix_report_tasks_id'), table_name='report_tasks')
    op.drop_index(op.f('ix_report_tasks_celery_task_id'), table_name='report_tasks')
    op.drop_table('report_tasks')
    # ### end Alembic commands ###
