name: CI Pipeline

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry and Dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-root --only main

      - name: Run Pytest
        run: poetry run pytest